version: "3.9"

services:
  # -----------------------------
  # PostgreSQL (Warehouse + Staging)
  # -----------------------------
  postgres:
    image: postgres:15
    container_name: telemetry_postgres
    restart: always
    environment:
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry
      POSTGRES_DB: telemetrydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # -----------------------------
  # MinIO (Object Storage)
  # -----------------------------
  minio:
    image: minio/minio:latest
    container_name: telemetry_minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    volumes:
      - minio_data:/data

  # -----------------------------
  # FastAPI Ingestion API
  # -----------------------------
  ingestion-api:
    build: ./ingestion-api
    container_name: telemetry_ingestion_api
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry
      POSTGRES_DB: telemetrydb
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    depends_on:
      - postgres
      - minio
    ports:
      - "8000:8000"

  # -----------------------------
  # Airflow
  # -----------------------------
  airflow:
    build: ./airflow
    env_file:
      - .env
    container_name: telemetry_airflow
    depends_on:
      - postgres
      - minio
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://telemetry:telemetry@postgres/telemetrydb
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
               airflow webserver & airflow scheduler"

volumes:
  pgdata:
  minio_data:
